
export const ArrayTasks = [
    {
      id: 1,
      title: "Task 1",
      desc: "Make this task quickly",
      tasked: "René Kemalandua",
      status: "Pending",
      created_at: "12-01-2012",
      delivery: "15-01-2012",
    },
    {
      id: 2,
      title: "Task 2",
      desc: "Make this task quickly",
      tasked: "René Kemalandua",
      status: "Pending",
      created_at: "12-01-2012",
      delivery: "15-01-2012",
    },
    {
      id: 3,
      title: "Task 3",
      desc: "Make this task quickly",
      tasked: "René Kemalandua",
      status: "Pending",
      created_at: "12-01-2012",
      delivery: "15-01-2012",
    },
    {
      id: 4,
      title: "Task 4",
      desc: "Make this task quickly",
      tasked: "René Kemalandua",
      status: "Pending",
      created_at: "12-01-2012",
      delivery: "15-01-2012",
    },
    {
      id: 5,
      title: "Task 5",
      desc: "Make this task quickly",
      tasked: "René Kemalandua",
      status: "Done",
      created_at: "12-01-2012",
      delivery: "15-01-2012",
    },
    {
      id: 6,
      title: "Task 6",
      desc: "Make this task quickly",
      tasked: "René Kemalandua",
      status: "Done",
      created_at: "12-01-2012",
      delivery: "15-01-2012",
    },
    {
      id: 7,
      title: "Task 7",
      desc: "Make this task quickly",
      tasked: "René Kemalandua",
      status: "Done",
      created_at: "12-01-2012",
      delivery: "15-01-2012",
    },
    {
      id: 8,
      title: "Task 8",
      desc: "Make this task quickly",
      tasked: "René Kemalandua",
      status: "Done",
      created_at: "12-01-2012",
      delivery: "15-01-2012",
    },
    {
      id: 9,
      title: "Task 9",
      desc: "Make this task quickly",
      tasked: "René Kemalandua",
      status: "Done",
      created_at: "12-01-2012",
      delivery: "15-01-2012",
    },
    {
      id: 10,
      title: "Task 10",
      desc: "Make this task quickly",
      tasked: "René Kemalandua",
      status: "Declined",
      created_at: "12-01-2012",
      delivery: "15-01-2012",
    },
    {
      id: 11,
      title: "Task 11",
      desc: "Make this task quickly",
      tasked: "René Kemalandua",
      status: "Declined",
      created_at: "12-01-2012",
      delivery: "15-01-2012",
    },
    {
      id: 12,
      title: "Task 12",
      desc: "Make this task quickly",
      tasked: "René Kemalandua",
      status: "Progress",
      created_at: "12-01-2012",
      delivery: "15-01-2012",
    },
    {
      id: 13,
      title: "Task 13",
      desc: "Make this task quickly",
      tasked: "René Kemalandua",
      status: "Progress",
      created_at: "12-01-2012",
      delivery: "15-01-2012",
    },
    {
      id: 14,
      title: "Task 14",
      desc: "Make this task quickly",
      tasked: "René Kemalandua",
      status: "Progress",
      created_at: "12-01-2012",
      delivery: "15-01-2012",
    },
  ];